// Maintain the agent-facing project guide separately from user-owned rules and configuration.

package project

import (
	"bytes"
	"context"
	"crypto/sha256"
	_ "embed"
	"fmt"
	"os"
	"strings"

	"github.com/fabricahq/code-rules/internal/filetxn"
)

// projectGuideTemplate ships with the binary; its shell examples are exercised by CLI integration tests.
//
//go:embed project-guide.md
var projectGuideTemplate string

// renderProjectGuide supplies the generated-file notice and ownership marker.
func renderProjectGuide() []byte {
	content := "> **Generated by Code Rules. Do not edit this file manually.**\n> Regenerate with `code-rules project build`. In Git repositories, build and sync work from any subdirectory; outside Git, run from the project root. Init and sync also refresh this guide. Keep project-specific notes in a separate file.\n\n" + projectGuideTemplate
	return stampProjectGuide([]byte(content))
}

// projectGuide owns README.md inside the project's .code-rules directory.
func projectGuide() (name string, content []byte) {
	return "README.md", renderProjectGuide()
}

// stampProjectGuide records the generated body's digest so later init runs can distinguish edits from older templates.
func stampProjectGuide(body []byte) []byte {
	return append([]byte(fmt.Sprintf("<!-- code-rules:project-guide sha256:%x -->\n", sha256.Sum256(body))), body...)
}

// unmodifiedProjectGuide accepts only our exact ownership header and an unchanged body; it is not an authenticity check.
func unmodifiedProjectGuide(data []byte) bool {
	_, body, found := bytes.Cut(data, []byte("\n"))
	return found && bytes.Equal(data, stampProjectGuide(body))
}

// prepareProjectGuide returns a safe creation or refresh, refusing to overwrite manually authored or edited bytes.
func prepareProjectGuide(ctx context.Context, root *os.Root) (*filetxn.File, error) {
	file, err := planProjectGuide(ctx, root)
	if err != nil {
		return nil, err
	}
	if bytes.Equal(file.Previous, file.Content) {
		return nil, nil
	}
	return file, nil
}

// planProjectGuide retains original bytes even for a current guide so builds can detect concurrent edits.
func planProjectGuide(ctx context.Context, root *os.Root) (*filetxn.File, error) {
	name, wanted := projectGuide()
	current, err := filetxn.ReadOptional(ctx, root, name)
	if err != nil {
		return nil, err
	}
	if !bytes.Equal(current, wanted) && current != nil && !unmodifiedProjectGuide(current) {
		return nil, failure("guide-edited", name+": unrecognized or manually edited project guide; preserve your notes in a separate file, move this guide aside, then rerun this command", nil)
	}
	return &filetxn.File{Path: name, Content: wanted, Previous: current}, nil
}

const localReadme = `# Local rules

A **local group** belongs to this project. Its metadata and rules live here, and you edit them directly. It needs no library or source declaration.

A **library group** comes from a versioned Git repository. The project selects it in its configuration and imports it with sync. Change its source selection or upstream library, then sync again; keep project-specific changes local.

## When groups share an ID

Local and library definitions can contribute to the same group, such as techs/go:

- Their rules are combined. Adding a local rule does not replace an imported rule, even when their filenames match.
- Local _group.json metadata takes precedence over library metadata for the group's name, description, and reading cue.
- Use explicit exclusions or replacements in the project configuration to remove or override imported rules.

## Manage local guidance

Follow [the project guide](../{{PROJECT_GUIDE}}) to add groups and rules. Keep rules within their group's scope and follow the [rule authoring rubric](https://github.com/fabricahq/code-rules/blob/main/docs/src/content/docs/reference/rule-authoring.md).

Complete drafts before building. Run code-rules project build after local edits, or code-rules project sync after changing a library source. Read the resulting [resolved rules](../generated/RULES.md) when working on the project.
`

// renderLocalReadme links newly initialized local guidance to the configuration's managed guide.
func renderLocalReadme() []byte {
	name, _ := projectGuide()
	return []byte(strings.ReplaceAll(localReadme, "{{PROJECT_GUIDE}}", name))
}

// includeProjectGuide stages only changed managed guidance and reports its configuration-relative path.
func includeProjectGuide(output map[filetxn.Target]map[string][]byte, guide *filetxn.File, changes *FileChanges) {
	if bytes.Equal(guide.Previous, guide.Content) {
		return
	}
	output[filetxn.Target(guide.Path)] = map[string][]byte{guide.Path: guide.Content}
	changes.Guide = &GuideChange{Path: guide.Path, Created: guide.Previous == nil}
}

// requireGuideUnchanged refuses edits made after guide ownership was established, including new files.
func requireGuideUnchanged(ctx context.Context, root *os.Root, guide *filetxn.File) error {
	current, err := filetxn.ReadOptional(ctx, root, guide.Path)
	if err != nil {
		return err
	}
	if (current == nil) != (guide.Previous == nil) || !bytes.Equal(current, guide.Previous) {
		return failure("concurrent-change", guide.Path+": project guide changed during the operation; retry after edits finish", nil)
	}
	return nil
}
