// Verify guide upgrades preserve authored files and refuse ambiguous ownership.

package project

import (
	"bytes"
	"context"
	"os"
	"path/filepath"
	"testing"
)

// TestProjectGuideRefresh updates an older generated guide while preserving configuration and local guidance byte for byte.
func TestProjectGuideRefresh(t *testing.T) {
	ctx := context.Background()
	directory := filepath.Join(t.TempDir(), ".code-rules")
	options := Options{Directory: filepath.Dir(directory)}
	if _, err := Initialize(ctx, options); err != nil {
		t.Fatal(err)
	}
	old := stampProjectGuide([]byte("# Earlier release guide\n"))
	config := []byte("{\n  \"schemaVersion\": 1, \"sources\": {}\n}\n")
	local := []byte("My local authoring notes.\n")
	for name, data := range map[string][]byte{"README.md": old, "config.json": config, "local/README.md": local} {
		if err := os.WriteFile(filepath.Join(directory, name), data, 0600); err != nil {
			t.Fatal(err)
		}
	}
	result, err := Initialize(ctx, options)
	if err != nil || len(result.Files) != 1 || result.Files[0] != filepath.Join(directory, "README.md") {
		t.Fatal(result, err)
	}
	for name, want := range map[string][]byte{"README.md": renderProjectGuide(), "config.json": config, "local/README.md": local} {
		got, err := os.ReadFile(filepath.Join(directory, name))
		if err != nil || !bytes.Equal(got, want) {
			t.Fatal(name, err)
		}
	}
	if result, err := Initialize(ctx, options); err != nil || len(result.Files) != 0 {
		t.Fatal(result, err)
	}
}

// TestProjectGuideRefusesUnmanagedFilesAndLinks verifies collisions fail before scaffolding is published.
func TestProjectGuideRefusesUnmanagedFilesAndLinks(t *testing.T) {
	for _, kind := range []string{"authored", "edited", "symlink"} {
		t.Run(kind, func(t *testing.T) {
			directory := filepath.Join(t.TempDir(), ".code-rules")
			if err := os.Mkdir(directory, 0700); err != nil {
				t.Fatal(err)
			}
			guide := filepath.Join(directory, "README.md")
			content := []byte("# My project notes\n")
			if kind == "edited" {
				content = append(stampProjectGuide([]byte("Old guide\n")), []byte("Edit\n")...)
			}
			if kind == "symlink" {
				target := filepath.Join(t.TempDir(), "notes.md")
				if err := os.WriteFile(target, content, 0600); err != nil {
					t.Fatal(err)
				}
				if err := os.Symlink(target, guide); err != nil {
					t.Fatal(err)
				}
			} else if err := os.WriteFile(guide, content, 0600); err != nil {
				t.Fatal(err)
			}
			if _, err := Initialize(context.Background(), Options{Directory: filepath.Dir(directory)}); err == nil {
				t.Fatal("expected refusal")
			}
			got, err := os.ReadFile(guide)
			if err != nil || !bytes.Equal(got, content) {
				t.Fatal("overwrote guide", err)
			}
			entries, err := os.ReadDir(directory)
			if err != nil || len(entries) != 1 {
				t.Fatal("published partial scaffolding", entries, err)
			}
		})
	}
}

// TestProjectGuideDefault agrees with the project operations' omitted configuration path.
func TestProjectGuideDefault(t *testing.T) {
	name, content := projectGuide()
	_, body, _ := bytes.Cut(content, []byte("\n"))
	if !bytes.HasPrefix(body, []byte("> **Generated by Code Rules. Do not edit this file manually.**\n")) || !bytes.Contains(body, []byte("code-rules project build")) {
		t.Fatal("missing managed guide notice", string(content))
	}
	if name != "README.md" || !bytes.Equal(content, renderProjectGuide()) {
		t.Fatal("default guide must match .code-rules/config.json", name)
	}
}
