/** @fileoverview Renders resolved rule groups and provenance into the complete generated file map. */

import type { BuildOutput, Group, ResolvedRules } from './types';
import { compare } from './validation';
import { escapeText, renderRule } from './markdown';

/** Render the selection index in group order, preserving each source's guidance order. */
function renderIndex(orderedGroups: ReadonlyArray<Group>): string {
  const index = [
    '# Code Rules',
    '',
    'This project uses [Fabrica Code Rules](https://github.com/fabricahq/code-rules) to declare the engineering best practices that people and agents should follow when writing or reviewing code.',
    'Each rule states an expectation, when it applies, and how to verify compliance.',
    '',
    "This file is the index to the project's adopted rules.",
    'The rules themselves are in the linked group files below, organized by technology or engineering practice.',
    "Each group file combines the active rules from shared libraries and local definitions, with the project's exclusions and replacements already applied.",
    '',
    '## How to use these rules',
    '',
    'Before writing code, use the descriptions below to find and read every group relevant to the task, technologies, and behavior involved.',
    'Apply each rule within its stated scope during implementation.',
    'During validation, check the code against those same rules and cite the rule IDs and evidence for any findings.',
    'Select practice groups by the behavior being changed: testing guidance can apply when adding production code, even if no test files have changed yet.',
    '',
    'This index and the linked group files are generated by Code Rules.',
    'To change the guidance, edit the source rules or project configuration and rebuild.',
  ];
  for (const [kind, title] of [
    ['techs', 'Technologies'],
    ['practices', 'Practices'],
  ]) {
    index.push('', `## ${title}`);
    const selected = orderedGroups.filter((group) =>
      group.id.startsWith(`${kind}/`),
    );
    if (selected.length === 0) index.push('', 'None selected.');
    for (const group of selected) {
      index.push('', `### [${group.id}](${group.id}.md)`);
      for (const guidance of group.guidance) {
        index.push(
          '',
          `**${guidance.source}: ${escapeText(guidance.metadata.name)}**`,
          '',
          escapeText(guidance.metadata.description),
        );
        if (guidance.metadata.whenToRead.length)
          index.push(
            '',
            ...guidance.metadata.whenToRead.map(
              (reason) => `- ${escapeText(reason)}`,
            ),
          );
      }
    }
  }
  index.push('', '[Source versions and rule origins](provenance.json).');
  return `${index.join('\n')}\n`;
}

/** Render one group's active rules in ID order without mutating the resolved collection. */
function renderGroup(group: Group): string {
  const title = [
    ...new Set(group.guidance.map(({ metadata }) => metadata.name)),
  ]
    .sort(compare)
    .map(escapeText)
    .join(' / ');
  const sections = [...group.rules]
    .sort((a, b) => compare(a.rule.id, b.rule.id))
    .map(renderRule);
  // Agents may open a group directly, so include its purpose and a route to project-wide guidance.
  const introduction = [
    `# ${title}`,
    '',
    `Group ID: \`${group.id}\``,
    '',
    "This file is a generated collection of the project's adopted engineering rules for this group, produced by [Fabrica Code Rules](https://github.com/fabricahq/code-rules).",
    "It aggregates rules from shared libraries and local definitions, with the project's exclusions and replacements already applied.",
    'Each rule below states an expectation, its scope, and how to verify compliance.',
    '',
    'Use these rules to guide implementation and to check the resulting work during validation.',
    'Apply every rule relevant to the task within its stated scope, and cite its source-qualified Rule ID when reporting findings.',
    'For project-wide instructions and help selecting other relevant technology or practice groups, read [RULES.md](../RULES.md).',
    'For source versions and rule origins, see [provenance.json](../provenance.json).',
    '',
    'To change this guidance, edit the source rules or project configuration and rebuild; edits to this generated file will be overwritten.',
  ];
  return `${introduction.join('\n')}\n\n${sections.length ? sections.join('\n\n---\n\n') : 'No active rules in this group.'}\n`;
}

/** Serialize source revisions and active rule origins in stable order, deriving rules from their groups. */
function renderProvenance(
  resolved: ResolvedRules,
  toolVersion: string,
): string {
  const provenance = {
    toolVersion,
    sources: resolved.sources,
    rules: resolved.groups
      .flatMap((group) => group.rules)
      .sort((a, b) => compare(a.rule.id, b.rule.id))
      .map((active) => ({
        id: active.rule.id,
        group: active.rule.group,
        origin: active.origin,
        upstream: active.upstream,
        replacementReason: active.reason,
      })),
  };
  return `${JSON.stringify(provenance, null, 2)}\n`;
}

/** Return path-sorted generated files without input mutation; invalid Markdown references throw BuildError. */
export function renderGeneratedFiles(
  resolved: ResolvedRules,
  toolVersion: string,
): BuildOutput {
  const output = new Map<string, string>([
    ['RULES.md', renderIndex(resolved.groups)],
  ]);
  for (const group of resolved.groups)
    output.set(`${group.id}.md`, renderGroup(group));
  output.set('provenance.json', renderProvenance(resolved, toolVersion));
  return {
    files: Object.fromEntries(
      [...output.entries()].sort(([a], [b]) => compare(a, b)),
    ),
  };
}
