/** @fileoverview Provides offline project generation and read-only consistency checks using verified vendor snapshots. */

import { buildRules } from './builds';
import { loadSnapshots } from './project-files/snapshots';
import { applyChanges, requireIdle, withWriter } from './project-files/apply';
import {
  projectLocation,
  readProject,
  requireActive,
  buildInput,
  generatedBytes,
  assertUnchanged,
  compareFiles,
} from './project-files/project';
import type { ProjectOptions, FileChanges } from './project-files/project';

/** Generate resolved rules offline and replace generated output only; reject altered or mismatched vendor snapshots. */
export async function buildProject(
  options: ProjectOptions = {},
): Promise<FileChanges> {
  requireActive(options);
  const { root, configPath } = await projectLocation(options);
  return withWriter(root, async () => {
    const state = await readProject(root, configPath);
    const snapshots = loadSnapshots(
      state.input,
      state.vendor?.files ?? new Map(),
    );
    const generated = generatedBytes(
      buildRules(buildInput(state, snapshots, options)).files,
    );
    const changes = compareFiles(
      state.generated?.files ?? new Map(),
      generated,
    );
    await applyChanges(root, { generated }, () =>
      assertUnchanged(root, configPath, state, options),
    );
    return changes;
  });
}

/** Compare expected generated bytes without network access or writes. Pending recovery or invalid vendor content is an error. */
export async function checkProject(
  options: ProjectOptions = {},
): Promise<FileChanges> {
  requireActive(options);
  const { root, configPath } = await projectLocation(options);
  await requireIdle(root);
  const state = await readProject(root, configPath);
  const snapshots = loadSnapshots(
    state.input,
    state.vendor?.files ?? new Map(),
  );
  const generated = generatedBytes(
    buildRules(buildInput(state, snapshots, options)).files,
  );
  const changes = compareFiles(state.generated?.files ?? new Map(), generated);
  await assertUnchanged(root, configPath, state, options);
  await requireIdle(root);
  return changes;
}
