name: Documentation
on:
  push:
  pull_request:
permissions:
  contents: read
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1
      - uses: oven-sh/setup-bun@v2.2.0
        with:
          bun-version: 1.4.2
      - uses: actions/setup-node@v6.5.0
        with:
          node-version: '26.9.0'
      - run: bun install --frozen-lockfile
      - run: bun run check
